export function find_icon(name) {
    const iconDef = {
        "skull" : 'U',
        "combat" : 'c',
        "willpower" : 'w',
        "intellect": 'i',
        "agility" : 'a',
        "cultist" : 'u',
        "tablet" : 't',
        "elder_thing": 'e',
        "tablet": 'E',
        "elder_sign": '\\',
        "auto_fail": 'f',
        "reaction" : '<',
        "action" : '>',
        "free" : '~',
        "survivor": 's',
        "seeker": 'S',
        "mystic": 'm',
        "guardian": 'g',
        "rogue": 'r',
        "Hand": 'h',
        "Arcane": ';',
        "neutral": '',
        "Accessory": '\'',
        "Ally": '\"',
        "Tarot": 'k',
        "arcane2": ":",
        "Hand x2": "H",
        "Body": "y",
        "rcore": "\\",
        "core": "\\",
        "wild":'l',
        "-2": 'X',
        "dwl": '',
        "ptc": '',
        "tcu": '',
        "tic": '',
        "tde": '',
        "tfa": '',
        "eoe":'',
        "tmm": '',
        "tece": '',
        "bota": '',
        "uau": '',
        "wda": '',
        "litas": ''
    };
    return iconDef[name];
}

export function investigator_data(){
    return ([
        {"pack_code":"core","pack_name":"Core Set","type_code":"investigator","type_name":"Investigator","faction_code":"guardian","faction_name":"Guardian","position":1,"exceptional":false,"myriad":false,"code":"01001","name":"Roland Banks","real_name":"Roland Banks","subname":"The Fed","text":"[reaction] After you defeat an enemy: Discover 1 clue at your location. (Limit once per round.)\n[elder_sign] effect: +1 for each clue on your location.","real_text":"[reaction] After you defeat an enemy: Discover 1 clue at your location. (Limit once per round.)\n[elder_sign] effect: +1 for each clue on your location.","quantity":1,"skill_willpower":3,"skill_intellect":3,"skill_combat":4,"skill_agility":2,"health":9,"health_per_investigator":false,"sanity":5,"deck_limit":1,"real_slot":"","traits":"Agency. Detective.","real_traits":"Agency. Detective.","deck_requirements":{"size":30,"card":{"01006":{"01006":"01006","98005":"98005","90030":"90030"},"01007":{"01007":"01007","98006":"98006","90031":"90031"}},"random":[{"target":"subtype","value":"basicweakness"}]},"deck_options":[{"faction":["guardian","neutral"],"level":{"min":0,"max":5}},{"faction":["seeker"],"level":{"min":0,"max":2}}],"flavor":"Everything by the book: every \"i\" dotted, every \"t\" crossed. It has worked, until now.","illustrator":"Magali Villeneuve","is_unique":true,"permanent":false,"double_sided":true,"back_text":"<b>Deck Size<\/b>: 30.\n<b>Deckbuilding Options<\/b>: Guardian cards ([guardian]) level 0-5, Seeker cards ([seeker]) level 0-2, Neutral cards level 0-5.\n<b>Deckbuilding Requirements<\/b> (do not count toward deck size): Roland's .38 Special, Cover Up, 1 random basic weakness.","back_flavor":"Roland had always taken comfort in procedure and rules. As an agent in the Bureau, he was relieved to have guidelines to follow in any given situation. But lately, his Federal Agent's Handbook had been entirely unhelpful given the cases he'd been assigned. Try as he might, Roland could find no mention of what to do when confronted with strange creatures, gates through time and space, or magic spells. If he hadn't seen it with his own eyes, he would never have believed it... and there's no way his superiors would understand. Roland knew he would have to handle this one himself.","octgn_id":"25f013a5-4ca2-4a34-9d03-e11e8ed93aaf:87041f6f-a325-4b5f-92b6-2df4d01790b1","url":"http:\/\/arkhamdb.com\/card\/01001","imagesrc":"\/bundles\/cards\/01001.png","backimagesrc":"\/bundles\/cards\/01001b.png","duplicated_by":["01501"],"alternated_by":["01501","90024"]},
        {"pack_code":"core","pack_name":"Core Set","type_code":"investigator","type_name":"Investigator","faction_code":"survivor","faction_name":"Survivor","position":5,"exceptional":false,"myriad":false,"code":"01005","name":"Wendy Adams","real_name":"Wendy Adams","subname":"The Urchin","text":"[reaction] When you reveal a chaos token, choose and discard 1 card from your hand: Cancel that chaos token and return it to the bag. Reveal a new chaos token. (Limit once per test\/ability.)\n[elder_sign] effect: +0. If Wendy's Amulet is in play, you automatically succeed instead.","real_text":"[reaction] When you reveal a chaos token, choose and discard 1 card from your hand: Cancel that chaos token and return it to the bag. Reveal a new chaos token. (Limit once per test\/ability.)\n[elder_sign] effect: +0. If Wendy's Amulet is in play, you automatically succeed instead.","quantity":1,"skill_willpower":4,"skill_intellect":3,"skill_combat":1,"skill_agility":4,"health":7,"health_per_investigator":false,"sanity":7,"deck_limit":1,"real_slot":"","traits":"Drifter.","real_traits":"Drifter.","deck_requirements":{"size":30,"card":{"01014":{"01014":"01014","90039":"90039"},"01015":{"01015":"01015","90040":"90040"}},"random":[{"target":"subtype","value":"basicweakness"}]},"deck_options":[{"faction":["survivor","neutral"],"level":{"min":0,"max":5}},{"faction":["rogue"],"level":{"min":0,"max":2}}],"illustrator":"Jacob Murray","is_unique":true,"permanent":false,"double_sided":true,"back_text":"<b>Deck Size<\/b>: 30.\n<b>Deckbuilding Options<\/b>: Survivor cards ([survivor]) level 0-5, Rogue cards ([rogue]) level 0-2, Neutral cards level 0-5.\n<b>Deckbuilding Requirements<\/b> (do not count toward deck size): Wendy's Amulet, Abandoned and Alone, 1 random basic weakness.","back_flavor":"Mama used to let Wendy play with her necklace when she was small. Mama would tell her stories, and Wendy would spin the necklace and watch as it glittered. Then, word came that her father had been lost at sea, and Mama started acting strange, drawing unusual symbols in chalk all over the house. They took Mama to the asylum, and Wendy went to the orphanage. Before they took her away, Mama gave her the necklace, to \"protect her.\" Wendy stayed in the orphanage for several years before running away, deciding that she could take better care of herself on her own.","octgn_id":"e8b6e380-16f3-40d7-af47-484db614ea18:86358d81-3a3e-40ba-999b-903a1c0d9365","url":"http:\/\/arkhamdb.com\/card\/01005","imagesrc":"\/bundles\/cards\/01005.png","backimagesrc":"\/bundles\/cards\/01005b.png","duplicated_by":["01505"],"alternated_by":["01505","90037"]},
        {"pack_code":"core","pack_name":"Core Set","type_code":"investigator","type_name":"Investigator","faction_code":"rogue","faction_name":"Rogue","position":3,"exceptional":false,"myriad":false,"code":"01003","name":"\"Skids\" O'Toole","real_name":"\"Skids\" O'Toole","subname":"The Ex-Con","text":"[free] During your turn, spend 2 resources: You may take an additional action this turn. (Limit once per turn.)\n[elder_sign] effect: +2. If you succeed, gain 2 resources.","real_text":"[free] During your turn, spend 2 resources: You may take an additional action this turn. (Limit once per turn.)\n[elder_sign] effect: +2. If you succeed, gain 2 resources.","quantity":1,"skill_willpower":2,"skill_intellect":3,"skill_combat":3,"skill_agility":4,"health":8,"health_per_investigator":false,"sanity":6,"deck_limit":1,"real_slot":"","traits":"Criminal.","real_traits":"Criminal.","deck_requirements":{"size":30,"card":{"01010":{"01010":"01010","90009":"90009"},"01011":{"01011":"01011","90010":"90010"}},"random":[{"target":"subtype","value":"basicweakness"}]},"deck_options":[{"faction":["rogue","neutral"],"level":{"min":0,"max":5}},{"faction":["guardian"],"level":{"min":0,"max":2}}],"flavor":"\"I didn't get out of the joint just to watch the world end.\"","illustrator":"Magali Villeneuve","is_unique":true,"permanent":false,"double_sided":true,"back_text":"<b>Deck Size<\/b>: 30.\n<b>Deckbuilding Options<\/b>: Rogue cards ([rogue]) level 0-5, Guardian cards ([guardian]) level 0-2, Neutral cards level 0-5.\n<b>Deckbuilding Requirements<\/b> (do not count toward deck size): On the Lam, Hospital Debts, 1 random basic weakness.","back_flavor":"Skids hadn't planned on a life of crime. But sometimes doing the right thing means getting your hands dirty. The cops didn't care that Skids needed the money for his mother's operation. His mother died of her illness during the second year of his sentence. His cellmate, Brad Hollins, told him there were worse fates than death. He ranted and raved in a quiet voice every evening about the \"Old Ones\" and told Skids about bizarre adventures he'd had while dreaming. Skids didn't give it much thought until the night he woke to the sight of his cellmate bursting into flames. When Skids was finally released, he returned to Arkham, looking for answers.","octgn_id":"4074eb1e-2341-4ff8-be20-d220621fa3c4:2df74e76-b199-433c-8f48-d2eaed044d56","url":"http:\/\/arkhamdb.com\/card\/01003","imagesrc":"\/bundles\/cards\/01003.png","backimagesrc":"\/bundles\/cards\/01003b.png","duplicated_by":["01503"],"alternated_by":["01503","90008"]},
        {"pack_code":"core","pack_name":"Core Set","type_code":"investigator","type_name":"Investigator","faction_code":"seeker","faction_name":"Seeker","position":2,"exceptional":false,"myriad":false,"code":"01002","name":"Daisy Walker","real_name":"Daisy Walker","subname":"The Librarian","text":"You may take an additional action during your turn, which can only be used on [[Tome]] [action] abilities.\n[elder_sign] effect: +0. If you succeed, draw 1 card for each [[Tome]] you control.","real_text":"You may take an additional action during your turn, which can only be used on [[Tome]] [action] abilities.\n[elder_sign] effect: +0. If you succeed, draw 1 card for each [[Tome]] you control.","quantity":1,"skill_willpower":3,"skill_intellect":5,"skill_combat":2,"skill_agility":2,"health":5,"health_per_investigator":false,"sanity":9,"deck_limit":1,"real_slot":"","traits":"Miskatonic.","real_traits":"Miskatonic.","deck_requirements":{"size":30,"card":{"01008":{"01008":"01008","90002":"90002"},"01009":{"01009":"01009","90003":"90003"}},"random":[{"target":"subtype","value":"basicweakness"}]},"deck_options":[{"faction":["seeker","neutral"],"level":{"min":0,"max":5}},{"faction":["mystic"],"level":{"min":0,"max":2}}],"flavor":"\"I know of books so powerful, they can rewrite reality.\"","illustrator":"Magali Villeneuve","is_unique":true,"permanent":false,"double_sided":true,"back_text":"<b>Deck Size<\/b>: 30.\n<b>Deckbuilding Options<\/b>: Seeker cards ([seeker]) level 0-5, Mystic cards ([mystic]) level 0-2, Neutral cards level 0-5.\n<b>Deckbuilding Requirements<\/b> (do not count toward deck size): Daisy\u2019s Tote Bag, The Necronomicon (John Dee Translation), 1 random basic weakness.","back_flavor":"As a respected librarian at Miskatonic University, Daisy had always felt that books were the most important thing in her life. She explored in fiction what she abhorred in life: horror, violence, fear. Then, she stumbled across the John Dee translation of the Necronomicon. It was blasphemous, unholy, and too awful to be read. But given her studies in obscure and occult subjects, Daisy knew there was more truth than fiction within the book's pages. She began to wonder what other secrets the restricted collection of the Orne Library held...","octgn_id":"53463cb2-2261-4d8b-b948-d8f7a926ed79:8c96b7d1-18b8-40eb-830c-47a85cd1180f","url":"http:\/\/arkhamdb.com\/card\/01002","imagesrc":"\/bundles\/cards\/01002.png","backimagesrc":"\/bundles\/cards\/01002b.png","duplicated_by":["01502"],"alternated_by":["01502","90001"]},
    ])
}

export function card_data(){
    return ([{"pack_code":"core","pack_name":"Core Set","type_code":"asset","type_name":"Asset","faction_code":"neutral","faction_name":"Neutral","position":6,"exceptional":false,"myriad":false,"code":"01006","name":"Roland's .38 Special","real_name":"Roland's .38 Special","cost":3,"text":"Roland Banks deck only.\nUses (4 ammo).\n[action] Spend 1 ammo: <b>Fight.<\/b> You get +1 [combat] for this attack (if there are 1 or more clues on your location, you get +3 [combat], instead). This attack deals +1 damage.","real_text":"Roland Banks deck only.\nUses (4 ammo).\n[action] Spend 1 ammo: <b>Fight.<\/b> You get +1 [combat] for this attack (if there are 1 or more clues on your location, you get +3 [combat], instead). This attack deals +1 damage.","errata_date":{"date":"2017-02-15 00:00:00.000000","timezone_type":3,"timezone":"UTC"},"quantity":1,"skill_combat":1,"skill_agility":1,"skill_wild":1,"health_per_investigator":false,"deck_limit":1,"slot":"Hand","real_slot":"Hand","traits":"Item. Weapon. Firearm.","real_traits":"Item. Weapon. Firearm.","restrictions":{"investigator":{"01001":"01001"}},"illustrator":"Tiziano Baracchi","is_unique":true,"permanent":false,"double_sided":false,"octgn_id":"4bb7b957-a180-4421-ad42-49704e11a3a5","url":"https:\/\/arkhamdb.com\/card\/01006","imagesrc":"\/bundles\/cards\/01006.png","duplicated_by":["01506"]},{"pack_code":"core","pack_name":"Core Set","type_code":"treachery","type_name":"Treachery","subtype_code":"weakness","subtype_name":"Weakness","faction_code":"neutral","faction_name":"Neutral","position":7,"exceptional":false,"myriad":false,"code":"01007","name":"Cover Up","real_name":"Cover Up","text":"<b>Revelation<\/b> - Put Cover Up into play in your threat area, with 3 clues on it.\n[reaction] When you would discover 1 or more clues at your location: Discard that many clues from Cover Up instead.\n<b>Forced<\/b> - When the game ends, if there are any clues on Cover Up: You suffer 1 mental trauma.","real_text":"<b>Revelation<\/b> - Put Cover Up into play in your threat area, with 3 clues on it.\n[reaction] When you would discover 1 or more clues at your location: Discard that many clues from Cover Up instead.\n<b>Forced<\/b> - When the game ends, if there are any clues on Cover Up: You suffer 1 mental trauma.","quantity":1,"health_per_investigator":false,"deck_limit":1,"real_slot":"","traits":"Task.","real_traits":"Task.","restrictions":{"investigator":{"01001":"01001"}},"illustrator":"Marcin Jakubowski","is_unique":false,"permanent":false,"double_sided":false,"octgn_id":"bc0a93e3-6643-49a2-9acc-8eaf681f4b2f","url":"https:\/\/arkhamdb.com\/card\/01007","imagesrc":"\/bundles\/cards\/01007.png","duplicated_by":["01507"]}
    ])
}